-- Run this in Supabase SQL Editor

create table doctors (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  specialty text,
  status text,
  rating numeric
);

-- Enable RLS
alter table doctors enable row level security;

create policy "Enable read access for all users"
on "public"."doctors"
as PERMISSIVE
for SELECT
to public
using (true);

-- Insert Initial Data
insert into doctors (name, specialty, status, rating) values
('Dr. Sarah Chen', 'Neurology', 'Available', 4.9),
('Dr. James Wilson', 'Cardiology', 'In Surgery', 4.8),
('Dr. Emily Davis', 'Trauma', 'Busy', 5.0),
('Dr. Michael Ross', 'General', 'Available', 4.7),
('Dr. Linda Kim', 'Pediatrics', 'On Break', 4.9);
