-- Run this in Supabase SQL Editor

create table patients (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  age text,
  risk text,
  score int,
  department text,
  symptoms text,
  status text default 'Waiting',
  reason text,
  deterioration_risk boolean
);

-- Optional: Enable RLS (Row Level Security) if you want public read/write for now
alter table patients enable row level security;

create policy "Enable read access for all users"
on "public"."patients"
as PERMISSIVE
for SELECT
to public
using (true);

create policy "Enable insert access for all users"
on "public"."patients"
as PERMISSIVE
for INSERT
to public
with check (true);
